# Generated by Django 4.0.6 on 2022-07-14 16:37

import FilDrop.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WalletAddress', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_name', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FilDrop.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserCollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=FilDrop.models.get_file_path, verbose_name='File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FilDrop.user')),
                ('usercollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FilDrop.usercollection')),
            ],
        ),
        migrations.CreateModel(
            name='ImageMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('weekno', models.CharField(blank=True, max_length=10, null=True)),
                ('metadata_date', models.DateField()),
                ('present_date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=False)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FilDrop.usercollectionimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FilDrop.user')),
                ('usercollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FilDrop.usercollection')),
            ],
        ),
    ]
